2025-01-07 12:56:38,317 INFO     24 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-07 12:56:44,161 INFO     24 init database on cluster mode successfully
2025-01-07 12:56:58,245 INFO     24 generated new fontManager
2025-01-07 12:57:10,444 INFO     24 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-07 12:57:10,445 INFO     24 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-07 12:57:10,446 INFO     24 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-07 12:57:10,453 INFO     24 GET http://es01:9200/ [status:200 duration:0.006s]
2025-01-07 12:57:10,456 INFO     24 HEAD http://es01:9200/ [status:200 duration:0.002s]
2025-01-07 12:57:10,457 INFO     24 Elasticsearch http://es01:9200 is healthy.
2025-01-07 12:57:10,460 WARNING  24 Load term.freq FAIL!
2025-01-07 12:57:10,463 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-07 12:57:10,466 WARNING  24 Load term.freq FAIL!
2025-01-07 12:57:10,469 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-07 12:57:10,469 INFO     24 MAX_CONTENT_LENGTH: 134217728
2025-01-07 12:57:10,470 INFO     24 SERVER_QUEUE_MAX_LEN: 1024
2025-01-07 12:57:10,470 INFO     24 SERVER_QUEUE_RETENTION: 3600
2025-01-07 12:57:10,470 INFO     24 MAX_FILE_COUNT_PER_USER: 0
2025-01-07 12:57:10,486 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 12:57:10,487 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T12:57:10.486+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 12:57:40,494 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 12:57:40,495 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T12:57:40.494+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 12:58:10,503 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 12:58:10,505 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T12:58:10.502+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 12:58:40,535 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 12:58:40,537 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T12:58:40.535+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 12:59:10,567 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 12:59:10,569 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T12:59:10.567+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 12:59:40,570 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 12:59:40,572 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T12:59:40.570+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 13:00:10,598 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 13:00:10,600 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T13:00:10.598+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 13:00:40,614 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 13:00:40,616 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T13:00:40.614+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 13:01:10,647 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 13:01:10,649 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T13:01:10.647+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 13:01:40,655 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 13:01:40,656 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T13:01:40.654+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 13:02:10,687 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 13:02:10,689 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T13:02:10.687+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-07 13:02:40,720 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-07 13:02:40,721 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-07T13:02:40.719+08:00", "boot_at": "2025-01-07T12:57:10.444+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:19:31,392 INFO     24 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-08 10:19:43,198 INFO     24 init database on cluster mode successfully
2025-01-08 10:20:04,004 INFO     24 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-08 10:20:04,005 INFO     24 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-08 10:20:04,006 INFO     24 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-08 10:20:04,015 INFO     24 GET http://es01:9200/ [status:200 duration:0.008s]
2025-01-08 10:20:04,019 INFO     24 HEAD http://es01:9200/ [status:200 duration:0.003s]
2025-01-08 10:20:04,020 INFO     24 Elasticsearch http://es01:9200 is healthy.
2025-01-08 10:20:04,024 WARNING  24 Load term.freq FAIL!
2025-01-08 10:20:04,028 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 10:20:04,036 WARNING  24 Load term.freq FAIL!
2025-01-08 10:20:04,040 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 10:20:04,041 INFO     24 MAX_CONTENT_LENGTH: 134217728
2025-01-08 10:20:04,042 INFO     24 SERVER_QUEUE_MAX_LEN: 1024
2025-01-08 10:20:04,042 INFO     24 SERVER_QUEUE_RETENTION: 3600
2025-01-08 10:20:04,043 INFO     24 MAX_FILE_COUNT_PER_USER: 0
2025-01-08 10:20:04,071 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:20:04,072 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:20:04.071+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:20:34,089 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:20:34,090 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:20:34.088+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:21:04,119 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:21:04,121 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:21:04.119+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:21:34,150 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:21:34,152 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:21:34.149+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:22:04,181 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:22:04,183 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:22:04.181+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:22:34,213 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:22:34,215 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:22:34.213+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:23:04,245 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:23:04,246 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:23:04.244+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:23:34,268 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:23:34,269 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:23:34.267+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:24:04,300 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:24:04,301 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:24:04.299+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:24:34,332 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:24:34,334 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:24:34.331+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:25:04,364 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:25:04,366 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:25:04.363+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:25:34,397 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:25:34,399 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:25:34.396+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:26:04,429 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:26:04,431 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:26:04.429+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:26:34,462 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:26:34,463 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:26:34.461+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:27:04,493 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:27:04,495 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:27:04.493+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:27:34,522 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:27:34,523 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:27:34.521+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:28:04,530 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:28:04,531 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:28:04.530+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:28:34,557 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:28:34,558 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:28:34.557+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:29:04,588 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:29:04,590 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:29:04.588+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:29:34,615 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:29:34,616 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:29:34.615+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:30:04,644 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:30:04,645 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:30:04.643+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:30:34,672 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:30:34,674 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:30:34.672+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:31:04,687 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:31:04,688 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:31:04.686+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:31:34,690 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:31:34,691 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:31:34.689+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:32:04,719 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:32:04,720 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:32:04.718+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:32:34,747 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:32:34,749 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:32:34.746+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:33:04,780 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:33:04,782 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:33:04.780+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:33:34,807 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:33:34,809 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:33:34.806+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:34:04,826 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:34:04,827 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:34:04.826+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:34:34,858 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:34:34,859 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:34:34.857+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:35:04,889 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:35:04,890 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:35:04.889+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:35:34,915 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:35:34,916 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:35:34.914+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:36:04,938 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:36:04,940 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:36:04.938+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:36:34,967 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:36:34,969 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:36:34.967+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:37:04,990 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:37:04,992 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:37:04.990+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:37:35,015 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:37:35,016 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:37:35.014+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:38:05,046 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:38:05,048 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:38:05.046+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:38:35,078 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:38:35,080 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:38:35.078+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:39:05,110 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:39:05,112 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:39:05.110+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:39:35,114 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:39:35,116 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:39:35.113+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:40:05,147 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:40:05,149 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:40:05.147+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:40:35,178 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:40:35,180 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:40:35.178+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:41:05,207 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:41:05,209 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:41:05.207+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:41:35,236 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:41:35,238 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:41:35.236+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:42:05,269 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:42:05,270 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:42:05.268+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:42:35,301 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:42:35,303 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:42:35.300+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:43:05,304 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:43:05,306 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:43:05.304+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:43:35,336 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:43:35,337 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:43:35.336+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:44:05,368 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:44:05,370 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:44:05.367+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:44:35,400 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:44:35,402 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:44:35.400+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:45:05,433 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:45:05,435 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:45:05.432+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:45:35,447 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:45:35,448 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:45:35.446+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:46:05,476 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:46:05,477 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:46:05.476+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:46:35,481 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:46:35,482 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:46:35.481+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:47:05,497 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:47:05,499 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:47:05.497+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:47:35,526 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:47:35,528 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:47:35.526+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:48:05,559 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:48:05,560 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:48:05.558+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:48:35,574 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:48:35,576 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:48:35.574+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:49:05,605 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:49:05,606 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:49:05.605+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:49:35,623 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:49:35,625 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:49:35.622+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:50:05,656 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:50:05,658 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:50:05.655+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:50:35,689 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:50:35,691 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:50:35.689+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:51:05,718 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:51:05,719 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:51:05.718+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:51:35,754 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:51:35,756 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:51:35.753+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:52:05,783 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:52:05,784 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:52:05.782+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:52:35,785 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:52:35,786 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:52:35.784+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:53:05,793 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:53:05,795 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:53:05.793+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:53:35,821 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:53:35,822 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:53:35.821+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:54:05,853 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:54:05,854 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:54:05.853+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:54:35,875 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:54:35,876 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:54:35.874+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:55:05,882 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:55:05,884 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:55:05.882+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:55:35,915 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:55:35,916 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:55:35.915+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:56:05,944 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:56:05,947 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:56:05.944+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:56:35,973 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:56:35,974 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:56:35.972+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:57:06,005 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:57:06,007 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:57:06.005+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:57:36,031 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:57:36,033 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:57:36.031+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:58:06,064 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:58:06,066 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:58:06.064+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:58:36,084 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:58:36,085 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:58:36.083+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:59:06,116 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:59:06,117 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:59:06.116+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 10:59:36,146 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 10:59:36,148 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T10:59:36.145+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:00:06,173 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:00:06,175 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:00:06.173+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:00:36,206 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:00:36,207 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:00:36.205+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:01:06,237 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:01:06,238 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:01:06.236+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:01:36,254 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:01:36,256 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:01:36.254+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:02:06,280 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:02:06,281 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:02:06.279+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:02:36,312 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:02:36,313 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:02:36.311+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:03:06,340 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:03:06,341 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:03:06.340+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:03:36,344 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:03:36,345 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:03:36.343+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:04:06,376 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:04:06,378 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:04:06.375+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:04:36,383 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:04:36,385 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:04:36.383+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:05:06,279 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:05:06,281 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:05:06.278+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:05:36,261 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:05:36,264 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:05:36.260+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:06:06,284 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:06:06,286 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:06:06.283+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:06:36,325 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:06:36,326 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:06:36.325+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:07:06,356 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:07:06,359 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:07:06.355+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:07:36,389 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:07:36,391 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:07:36.389+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:08:06,408 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:08:06,409 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:08:06.408+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:08:36,427 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:08:36,428 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:08:36.426+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:09:06,455 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:09:06,456 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:09:06.455+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:09:36,487 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:09:36,489 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:09:36.487+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:10:06,518 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:10:06,519 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:10:06.518+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:10:36,549 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:10:36,550 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:10:36.549+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:11:06,577 WARNING  24 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:11:06,578 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:11:06.576+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:11:33,238 INFO     24 handle_task begin for task {"id": "43327c54cd6e11efb3920242ac130006", "doc_id": "3eb7348acd6e11ef8ca80242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "5923c7a8cd6811efb0e00242ac130006", "parser_id": "naive", "parser_config": {"pages": [[1, 1000000]]}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "English", "embd_id": "", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736305892936}
2025-01-08 11:11:33,271 INFO     24 From minio(0.0172554810001202) xlsl8.pdf/xlsl8.pdf
2025-01-08 11:11:36,630 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:11:36.613+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 1, "lag": 0, "done": 0, "failed": 0, "current": {"id": "43327c54cd6e11efb3920242ac130006", "doc_id": "3eb7348acd6e11ef8ca80242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "5923c7a8cd6811efb0e00242ac130006", "parser_id": "naive", "parser_config": {"pages": [[1, 1000000]]}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "English", "embd_id": "", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736305892936}}
2025-01-08 11:11:39,141 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: None, progress_msg: 11:11:39 Page(1~4): OCR started
2025-01-08 11:11:43,273 WARNING  24 Miss outlines
2025-01-08 11:11:52,989 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: None, progress_msg: 11:11:52 Page(1~4): OCR finished (13.85s)
2025-01-08 11:11:52,998 INFO     24 OCR(0~3): 13.86s
2025-01-08 11:11:57,522 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: 0.63, progress_msg: 11:11:57 Page(1~4): Layout analysis (4.52s)
2025-01-08 11:11:57,693 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: 0.65, progress_msg: 11:11:57 Page(1~4): Table analysis (0.16s)
2025-01-08 11:11:57,705 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: 0.67, progress_msg: 11:11:57 Page(1~4): Text merged (0.00s)
2025-01-08 11:11:57,765 INFO     24 layouts cost: 18.628738586000054s
2025-01-08 11:11:57,850 INFO     24 naive_merge(xlsl8.pdf): 0.06864068699997006
2025-01-08 11:11:57,851 INFO     24 Chunking(24.597804756000187) xlsl8.pdf/xlsl8.pdf done
2025-01-08 11:11:57,946 INFO     24 MINIO PUT(xlsl8.pdf):0.05068122600005154
2025-01-08 11:11:57,946 INFO     24 Build document xlsl8.pdf: 24.69s
2025-01-08 11:11:57,950 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: None, progress_msg: 11:11:57 Page(1~4): Generate 8 chunks
2025-01-08 11:11:57,961 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: -1, progress_msg: 11:11:57 Page(1~4): [ERROR]Generate embedding error:list indices must be integers or slices, not tuple
2025-01-08 11:11:57,973 ERROR    24 Generate embedding error:list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7f7aa9c40160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7f7aa9bfc1f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:11:57,980 INFO     24 set_progress(43327c54cd6e11efb3920242ac130006), progress: -1, progress_msg: 11:11:57 [ERROR]handle_task got exception, please check log
2025-01-08 11:11:57,989 ERROR    24 handle_task got exception for task {"id": "43327c54cd6e11efb3920242ac130006", "doc_id": "3eb7348acd6e11ef8ca80242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "5923c7a8cd6811efb0e00242ac130006", "parser_id": "naive", "parser_config": {"pages": [[1, 1000000]]}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "English", "embd_id": "", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736305892936}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 513, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7f7aa9c40160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7f7aa9bfc1f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:12:02,417 INFO     24 handle_task begin for task {"id": "54c1ce16cd6e11ef9f040242ac130006", "doc_id": "3eb7348acd6e11ef8ca80242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "5923c7a8cd6811efb0e00242ac130006", "parser_id": "naive", "parser_config": {"pages": [[1, 1000000]]}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736305922398}
2025-01-08 11:12:02,433 INFO     24 From minio(0.0062133709998306585) xlsl8.pdf/xlsl8.pdf
2025-01-08 11:12:03,560 INFO     24 set_progress(54c1ce16cd6e11ef9f040242ac130006), progress: None, progress_msg: 11:12:03 Page(1~4): OCR started
2025-01-08 11:12:06,705 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:12:06.694+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 1, "lag": 0, "done": 0, "failed": 1, "current": {"id": "54c1ce16cd6e11ef9f040242ac130006", "doc_id": "3eb7348acd6e11ef8ca80242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "5923c7a8cd6811efb0e00242ac130006", "parser_id": "naive", "parser_config": {"pages": [[1, 1000000]]}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736305922398}}
2025-01-08 11:12:07,813 WARNING  24 Miss outlines
2025-01-08 11:12:16,570 INFO     24 set_progress(54c1ce16cd6e11ef9f040242ac130006), progress: None, progress_msg: 11:12:16 Page(1~4): OCR finished (13.01s)
2025-01-08 11:12:16,578 INFO     24 OCR(0~3): 13.02s
2025-01-08 11:14:50,849 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:12:36.889+08:00", "boot_at": "2025-01-08T10:20:04.004+08:00", "pending": 1, "lag": 0, "done": 0, "failed": 1, "current": {"id": "54c1ce16cd6e11ef9f040242ac130006", "doc_id": "3eb7348acd6e11ef8ca80242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "5923c7a8cd6811efb0e00242ac130006", "parser_id": "naive", "parser_config": {"pages": [[1, 1000000]]}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736305922398}}
2025-01-08 11:27:50,882 INFO     23 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-08 11:27:59,356 INFO     23 init database on cluster mode successfully
2025-01-08 11:28:24,903 INFO     23 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-08 11:28:24,904 INFO     23 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-08 11:28:24,904 INFO     23 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-08 11:28:24,913 INFO     23 GET http://es01:9200/ [status:200 duration:0.007s]
2025-01-08 11:28:24,917 INFO     23 HEAD http://es01:9200/ [status:200 duration:0.003s]
2025-01-08 11:28:24,918 INFO     23 Elasticsearch http://es01:9200 is healthy.
2025-01-08 11:28:24,922 WARNING  23 Load term.freq FAIL!
2025-01-08 11:28:24,925 WARNING  23 Realtime synonym is disabled, since no redis connection.
2025-01-08 11:28:24,929 WARNING  23 Load term.freq FAIL!
2025-01-08 11:28:24,933 WARNING  23 Realtime synonym is disabled, since no redis connection.
2025-01-08 11:28:24,934 INFO     23 MAX_CONTENT_LENGTH: 134217728
2025-01-08 11:28:24,934 INFO     23 SERVER_QUEUE_MAX_LEN: 1024
2025-01-08 11:28:24,934 INFO     23 SERVER_QUEUE_RETENTION: 3600
2025-01-08 11:28:24,935 INFO     23 MAX_FILE_COUNT_PER_USER: 0
2025-01-08 11:28:24,941 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:28:24,942 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:28:24.941+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:28:54,909 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:28:54,910 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:28:54.908+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:29:25,008 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:29:25,010 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:29:25.008+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:29:55,040 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:29:55,041 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:29:55.039+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:30:25,076 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:30:25,078 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:30:25.075+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:30:55,112 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:30:55,113 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:30:55.111+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:31:25,140 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:31:25,141 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:31:25.140+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:31:55,171 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:31:55,172 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:31:55.171+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:32:25,200 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:32:25,202 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:32:25.200+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:32:55,233 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:32:55,235 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:32:55.232+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:33:25,256 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:33:25,258 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:33:25.256+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:33:55,259 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:33:55,261 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:33:55.259+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:34:25,290 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:34:25,291 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:34:25.289+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:34:55,319 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:34:55,320 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:34:55.318+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:35:25,347 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:35:25,349 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:35:25.347+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:35:55,380 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:35:55,382 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:35:55.379+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:36:25,412 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2025-01-08 11:36:25,413 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:36:25.412+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:36:34,782 INFO     23 handle_task begin for task {"id": "c1ef58d4cd7111efa86d0242ac130006", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736307394053}
2025-01-08 11:36:34,798 INFO     23 From minio(0.008336084999996274) xlsl8.pdf/xlsl8.pdf
2025-01-08 11:36:38,055 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: None, progress_msg: 11:36:38 Page(1~4): OCR started
2025-01-08 11:36:40,874 WARNING  23 Miss outlines
2025-01-08 11:36:48,501 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: None, progress_msg: 11:36:48 Page(1~4): OCR finished (10.46s)
2025-01-08 11:36:48,509 INFO     23 OCR(0~3): 10.47s
2025-01-08 11:36:52,178 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: 0.63, progress_msg: 11:36:52 Page(1~4): Layout analysis (3.66s)
2025-01-08 11:36:52,352 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: 0.65, progress_msg: 11:36:52 Page(1~4): Table analysis (0.16s)
2025-01-08 11:36:52,365 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: 0.67, progress_msg: 11:36:52 Page(1~4): Text merged (0.00s)
2025-01-08 11:36:52,425 INFO     23 layouts cost: 14.387263239000049s
2025-01-08 11:36:52,481 INFO     23 naive_merge(xlsl8.pdf): 0.04472728799999004
2025-01-08 11:36:52,482 INFO     23 Chunking(17.706816295000067) xlsl8.pdf/xlsl8.pdf done
2025-01-08 11:36:52,568 INFO     23 MINIO PUT(xlsl8.pdf):0.04544685500002288
2025-01-08 11:36:52,569 INFO     23 Build document xlsl8.pdf: 17.79s
2025-01-08 11:36:52,572 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: None, progress_msg: 11:36:52 Page(1~4): Generate 8 chunks
2025-01-08 11:36:52,581 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: -1, progress_msg: 11:36:52 Page(1~4): [ERROR]Generate embedding error:list indices must be integers or slices, not tuple
2025-01-08 11:36:52,590 ERROR    23 Generate embedding error:list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7f6554820160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7f65547dc1f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:36:52,596 INFO     23 set_progress(c1ef58d4cd7111efa86d0242ac130006), progress: -1, progress_msg: 11:36:52 [ERROR]handle_task got exception, please check log
2025-01-08 11:36:52,605 ERROR    23 handle_task got exception for task {"id": "c1ef58d4cd7111efa86d0242ac130006", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736307394053}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 513, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7f6554820160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7f65547dc1f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:36:55,421 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:36:55.420+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:37:25,465 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:37:25.465+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:37:55,496 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:37:55.495+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:38:25,525 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:38:25.524+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:38:55,556 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:38:55.556+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:39:25,587 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:39:25.586+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:39:55,618 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:39:55.617+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:40:25,648 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:40:25.648+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:40:55,656 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:40:55.655+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:41:25,666 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:41:25.665+08:00", "boot_at": "2025-01-08T11:28:24.902+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:41:40,862 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Connection closed by server.
Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 205, in queue_consumer
    messages = self.REDIS.xreadgroup(**args)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 4017, in xreadgroup
    return self.execute_command("XREADGROUP", *pieces)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 570, in execute_command
    response = conn.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 65, in call_with_retry
    fail(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 574, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 556, in _disconnect_raise
    raise error
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 571, in <lambda>
    lambda: self._send_command_parse_response(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 543, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 590, in parse_response
    response = connection.read_response()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 546, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
valkey.exceptions.ConnectionError: Connection closed by server.
2025-01-08 11:41:41,871 ERROR    23 RedisDB.get_unacked_for task_consumer_0 got exception: Error 111 connecting to redis:6379. Connection refused.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 728, in _connect
    raise err
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 716, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error 111 connecting to redis:6379. Connection refused.
2025-01-08 11:41:41,873 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error 111 connecting to redis:6379. Connection refused.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 728, in _connect
    raise err
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 716, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error 111 connecting to redis:6379. Connection refused.
2025-01-08 11:41:54,730 INFO     23 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-08 11:42:01,205 INFO     23 init database on cluster mode successfully
2025-01-08 11:42:18,831 INFO     23 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-08 11:42:18,832 INFO     23 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-08 11:42:18,833 INFO     23 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-08 11:42:18,842 INFO     23 GET http://es01:9200/ [status:200 duration:0.007s]
2025-01-08 11:42:18,846 INFO     23 HEAD http://es01:9200/ [status:200 duration:0.003s]
2025-01-08 11:42:18,847 INFO     23 Elasticsearch http://es01:9200 is healthy.
2025-01-08 11:42:18,851 WARNING  23 Load term.freq FAIL!
2025-01-08 11:42:18,855 WARNING  23 Realtime synonym is disabled, since no redis connection.
2025-01-08 11:42:18,859 WARNING  23 Load term.freq FAIL!
2025-01-08 11:42:18,862 WARNING  23 Realtime synonym is disabled, since no redis connection.
2025-01-08 11:42:18,863 INFO     23 MAX_CONTENT_LENGTH: 134217728
2025-01-08 11:42:18,863 INFO     23 SERVER_QUEUE_MAX_LEN: 1024
2025-01-08 11:42:18,864 INFO     23 SERVER_QUEUE_RETENTION: 3600
2025-01-08 11:42:18,865 INFO     23 MAX_FILE_COUNT_PER_USER: 0
2025-01-08 11:42:18,871 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:42:18.870+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:42:41,112 INFO     23 handle_task begin for task {"id": "9ca6202acd7211ef9eaf0242ac130006", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736307761026}
2025-01-08 11:42:41,130 INFO     23 From minio(0.007992249999915657) xlsl8.pdf/xlsl8.pdf
2025-01-08 11:42:51,636 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:42:50.822+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 1, "lag": 0, "done": 0, "failed": 0, "current": {"id": "9ca6202acd7211ef9eaf0242ac130006", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736307761026}}
2025-01-08 11:42:52,779 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: None, progress_msg: 11:42:52 Page(1~4): OCR started
2025-01-08 11:42:56,095 WARNING  23 Miss outlines
2025-01-08 11:43:04,006 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: None, progress_msg: 11:43:04 Page(1~4): OCR finished (11.23s)
2025-01-08 11:43:04,015 INFO     23 OCR(0~3): 11.24s
2025-01-08 11:43:07,831 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: 0.63, progress_msg: 11:43:07 Page(1~4): Layout analysis (3.81s)
2025-01-08 11:43:07,998 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: 0.65, progress_msg: 11:43:07 Page(1~4): Table analysis (0.15s)
2025-01-08 11:43:08,010 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: 0.67, progress_msg: 11:43:08 Page(1~4): Text merged (0.00s)
2025-01-08 11:43:08,067 INFO     23 layouts cost: 15.29116207300001s
2025-01-08 11:43:08,116 INFO     23 naive_merge(xlsl8.pdf): 0.03936821099989629
2025-01-08 11:43:08,116 INFO     23 Chunking(26.99562200699995) xlsl8.pdf/xlsl8.pdf done
2025-01-08 11:43:08,204 INFO     23 MINIO PUT(xlsl8.pdf):0.049790172000143684
2025-01-08 11:43:08,204 INFO     23 Build document xlsl8.pdf: 27.08s
2025-01-08 11:43:08,208 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: None, progress_msg: 11:43:08 Page(1~4): Generate 8 chunks
2025-01-08 11:43:08,218 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: -1, progress_msg: 11:43:08 Page(1~4): [ERROR]Generate embedding error:list indices must be integers or slices, not tuple
2025-01-08 11:43:08,229 ERROR    23 Generate embedding error:list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7fda7e4b0160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7fda7e5ec1f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:43:08,234 INFO     23 set_progress(9ca6202acd7211ef9eaf0242ac130006), progress: -1, progress_msg: 11:43:08 [ERROR]handle_task got exception, please check log
2025-01-08 11:43:08,243 ERROR    23 handle_task got exception for task {"id": "9ca6202acd7211ef9eaf0242ac130006", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736307761026}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 513, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7fda7e4b0160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7fda7e5ec1f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:43:21,673 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:43:21.672+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:43:51,697 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:43:51.696+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:44:21,719 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:44:21.718+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:44:51,726 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:44:51.725+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:45:21,757 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:45:21.756+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:45:51,788 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:45:51.787+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:46:21,814 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:46:21.814+08:00", "boot_at": "2025-01-08T11:42:18.831+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:46:26,907 ERROR    23 RedisDB.get_unacked_for task_consumer_0 got exception: Error 111 connecting to redis:6379. Connection refused.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1116, in get_connection
    if connection.can_read() and connection.client_cache is None:
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 524, in can_read
    return self._parser.can_read(timeout)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/base.py", line 128, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 95, in can_read
    return bool(self.unread_bytes()) or self._read_from_socket(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
valkey.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 728, in _connect
    raise err
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 716, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1120, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error 111 connecting to redis:6379. Connection refused.
2025-01-08 11:46:26,913 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error 111 connecting to redis:6379. Connection refused.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 728, in _connect
    raise err
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 716, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error 111 connecting to redis:6379. Connection refused.
2025-01-08 11:46:31,673 ERROR    23 RedisDB.get_unacked_for task_consumer_0 got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:46:35,386 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:47:06,075 INFO     23 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-08 11:47:35,833 INFO     23 init database on cluster mode successfully
2025-01-08 11:47:51,595 INFO     23 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-08 11:47:51,596 INFO     23 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-08 11:47:51,596 INFO     23 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-08 11:47:51,606 INFO     23 GET http://es01:9200/ [status:200 duration:0.008s]
2025-01-08 11:47:51,613 INFO     23 HEAD http://es01:9200/ [status:200 duration:0.005s]
2025-01-08 11:47:51,614 INFO     23 Elasticsearch http://es01:9200 is healthy.
2025-01-08 11:47:51,619 WARNING  23 Load term.freq FAIL!
2025-01-08 11:47:51,623 WARNING  23 Realtime synonym is disabled, since no redis connection.
2025-01-08 11:47:51,628 WARNING  23 Load term.freq FAIL!
2025-01-08 11:47:51,631 WARNING  23 Realtime synonym is disabled, since no redis connection.
2025-01-08 11:47:51,632 INFO     23 MAX_CONTENT_LENGTH: 134217728
2025-01-08 11:47:51,632 INFO     23 SERVER_QUEUE_MAX_LEN: 1024
2025-01-08 11:47:51,633 INFO     23 SERVER_QUEUE_RETENTION: 3600
2025-01-08 11:47:51,633 INFO     23 MAX_FILE_COUNT_PER_USER: 0
2025-01-08 11:47:55,374 WARNING  23 RedisDB.sadd TASKEXE got exception: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:47:55,374 ERROR    23 RedisDB.get_unacked_for task_consumer_0 got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:47:59,090 WARNING  23 RedisDB.queue_info rag_flow_svr_queue got exception: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:47:59,090 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:48:02,810 WARNING  23 RedisDB.zadd task_consumer_0 got exception: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:48:02,812 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:47:55.375+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:48:03,823 ERROR    23 RedisDB.get_unacked_for task_consumer_0 got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:48:06,530 WARNING  23 RedisDB.zcount task_consumer_0 got exception: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:48:07,540 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:48:36,536 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:48:36.534+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 11:48:49,005 INFO     23 handle_task begin for task {"id": "77fc4beacd7311ef81f70242ac130002", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736308128984}
2025-01-08 11:48:49,026 INFO     23 From minio(0.00878145499996208) xlsl8.pdf/xlsl8.pdf
2025-01-08 11:48:52,396 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: None, progress_msg: 11:48:52 Page(1~4): OCR started
2025-01-08 11:48:55,431 WARNING  23 Miss outlines
2025-01-08 11:49:03,602 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: None, progress_msg: 11:49:03 Page(1~4): OCR finished (11.21s)
2025-01-08 11:49:03,609 INFO     23 OCR(0~3): 11.22s
2025-01-08 11:49:06,569 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:49:06.566+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 1, "lag": 0, "done": 0, "failed": 0, "current": {"id": "77fc4beacd7311ef81f70242ac130002", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736308128984}}
2025-01-08 11:49:07,344 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: 0.63, progress_msg: 11:49:07 Page(1~4): Layout analysis (3.73s)
2025-01-08 11:49:07,515 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: 0.65, progress_msg: 11:49:07 Page(1~4): Table analysis (0.16s)
2025-01-08 11:49:07,526 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: 0.67, progress_msg: 11:49:07 Page(1~4): Text merged (0.00s)
2025-01-08 11:49:07,575 INFO     23 layouts cost: 15.183359786999972s
2025-01-08 11:49:07,683 INFO     23 naive_merge(xlsl8.pdf): 0.09874568100008219
2025-01-08 11:49:07,684 INFO     23 Chunking(18.6672957830001) xlsl8.pdf/xlsl8.pdf done
2025-01-08 11:49:07,806 INFO     23 MINIO PUT(xlsl8.pdf):0.07502031999956671
2025-01-08 11:49:07,806 INFO     23 Build document xlsl8.pdf: 18.79s
2025-01-08 11:49:07,809 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: None, progress_msg: 11:49:07 Page(1~4): Generate 8 chunks
2025-01-08 11:49:07,822 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: -1, progress_msg: 11:49:07 Page(1~4): [ERROR]Generate embedding error:list indices must be integers or slices, not tuple
2025-01-08 11:49:07,831 ERROR    23 Generate embedding error:list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7f1d5f468160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7f1d5f6681f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:49:07,837 INFO     23 set_progress(77fc4beacd7311ef81f70242ac130002), progress: -1, progress_msg: 11:49:07 [ERROR]handle_task got exception, please check log
2025-01-08 11:49:07,847 ERROR    23 handle_task got exception for task {"id": "77fc4beacd7311ef81f70242ac130002", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736308128984}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 513, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7f1d5f468160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7f1d5f6681f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 11:49:36,599 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:49:36.599+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:50:06,604 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:50:06.603+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:50:36,612 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:50:36.611+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:51:06,643 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:51:06.642+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:51:36,645 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:51:36.644+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:52:06,676 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:52:06.676+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:52:36,708 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:52:36.707+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:53:06,730 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:53:06.729+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:53:36,739 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:53:36.738+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:54:06,769 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:54:06.768+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:54:36,801 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:54:36.800+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:55:06,832 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:55:06.831+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:55:36,860 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:55:36.860+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:56:06,889 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:56:06.889+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:56:36,894 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:56:36.893+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:57:06,925 INFO     23 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T11:57:06.925+08:00", "boot_at": "2025-01-08T11:47:51.594+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 11:57:30,409 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Connection closed by server.
Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 205, in queue_consumer
    messages = self.REDIS.xreadgroup(**args)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 4017, in xreadgroup
    return self.execute_command("XREADGROUP", *pieces)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 570, in execute_command
    response = conn.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 65, in call_with_retry
    fail(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 574, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 556, in _disconnect_raise
    raise error
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 571, in <lambda>
    lambda: self._send_command_parse_response(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 543, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 590, in parse_response
    response = connection.read_response()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 546, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
valkey.exceptions.ConnectionError: Connection closed by server.
2025-01-08 11:57:35,150 ERROR    23 RedisDB.get_unacked_for task_consumer_0 got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 11:57:38,876 ERROR    23 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 12:06:56,192 INFO     24 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-08 12:07:01,768 INFO     24 init database on cluster mode successfully
2025-01-08 12:07:13,369 INFO     24 generated new fontManager
2025-01-08 12:07:24,448 INFO     24 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-08 12:07:24,449 INFO     24 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-08 12:07:24,451 INFO     24 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-08 12:07:24,459 INFO     24 GET http://es01:9200/ [status:200 duration:0.006s]
2025-01-08 12:07:24,463 INFO     24 HEAD http://es01:9200/ [status:200 duration:0.003s]
2025-01-08 12:07:24,463 INFO     24 Elasticsearch http://es01:9200 is healthy.
2025-01-08 12:07:24,468 WARNING  24 Load term.freq FAIL!
2025-01-08 12:07:24,471 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 12:07:24,475 WARNING  24 Load term.freq FAIL!
2025-01-08 12:07:24,478 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 12:07:24,479 INFO     24 MAX_CONTENT_LENGTH: 134217728
2025-01-08 12:07:24,479 INFO     24 SERVER_QUEUE_MAX_LEN: 1024
2025-01-08 12:07:24,480 INFO     24 SERVER_QUEUE_RETENTION: 3600
2025-01-08 12:07:24,480 INFO     24 MAX_FILE_COUNT_PER_USER: 0
2025-01-08 12:07:24,489 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:07:24.488+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:07:54,520 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:07:54.519+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:08:24,530 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:08:24.529+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:08:32,996 INFO     24 handle_task begin for task {"id": "39b2d81acd7611efa0930242ac130006", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736309312974}
2025-01-08 12:08:33,020 INFO     24 From minio(0.01001733199973387) xlsl8.pdf/xlsl8.pdf
2025-01-08 12:08:36,239 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: None, progress_msg: 12:08:36 Page(1~4): OCR started
2025-01-08 12:08:39,161 WARNING  24 Miss outlines
2025-01-08 12:08:47,354 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: None, progress_msg: 12:08:47 Page(1~4): OCR finished (11.12s)
2025-01-08 12:08:47,361 INFO     24 OCR(0~3): 11.13s
2025-01-08 12:08:51,197 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: 0.63, progress_msg: 12:08:51 Page(1~4): Layout analysis (3.83s)
2025-01-08 12:08:51,374 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: 0.65, progress_msg: 12:08:51 Page(1~4): Table analysis (0.16s)
2025-01-08 12:08:51,389 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: 0.67, progress_msg: 12:08:51 Page(1~4): Text merged (0.00s)
2025-01-08 12:08:51,465 INFO     24 layouts cost: 15.229380522000156s
2025-01-08 12:08:51,604 INFO     24 naive_merge(xlsl8.pdf): 0.12162177900017923
2025-01-08 12:08:51,604 INFO     24 Chunking(18.594547994000095) xlsl8.pdf/xlsl8.pdf done
2025-01-08 12:08:51,722 INFO     24 MINIO PUT(xlsl8.pdf):0.07034716899943305
2025-01-08 12:08:51,722 INFO     24 Build document xlsl8.pdf: 18.71s
2025-01-08 12:08:51,726 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: None, progress_msg: 12:08:51 Page(1~4): Generate 8 chunks
2025-01-08 12:08:51,740 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: -1, progress_msg: 12:08:51 Page(1~4): [ERROR]Generate embedding error:list indices must be integers or slices, not tuple
2025-01-08 12:08:51,751 ERROR    24 Generate embedding error:list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7fc2fdc5c280>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7fc2fdd9c310>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 12:08:51,761 INFO     24 set_progress(39b2d81acd7611efa0930242ac130006), progress: -1, progress_msg: 12:08:51 [ERROR]handle_task got exception, please check log
2025-01-08 12:08:51,773 ERROR    24 handle_task got exception for task {"id": "39b2d81acd7611efa0930242ac130006", "doc_id": "bf06d7d2cd7111ef8c650242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "870d6b52cd7111ef9e010242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736309312974}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 513, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7fc2fdc5c280>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7fc2fdd9c310>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 12:08:54,562 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:08:54.561+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:09:24,594 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:09:24.593+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:09:54,622 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:09:54.621+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:10:24,654 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:10:24.653+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:10:54,665 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:10:54.664+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:11:24,691 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:11:24.690+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:11:54,719 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:11:54.718+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:12:24,724 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:12:24.722+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:12:54,755 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:12:54.754+08:00", "boot_at": "2025-01-08T12:07:24.448+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:13:11,664 ERROR    24 RedisDB.queue_consumer rag_flow_svr_queue got exception: Connection closed by server.
Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 205, in queue_consumer
    messages = self.REDIS.xreadgroup(**args)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 4017, in xreadgroup
    return self.execute_command("XREADGROUP", *pieces)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 570, in execute_command
    response = conn.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 65, in call_with_retry
    fail(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 574, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 556, in _disconnect_raise
    raise error
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 571, in <lambda>
    lambda: self._send_command_parse_response(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 543, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 590, in parse_response
    response = connection.read_response()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 546, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
valkey.exceptions.ConnectionError: Connection closed by server.
2025-01-08 12:13:30,487 INFO     24 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-08 12:13:36,379 INFO     24 init database on cluster mode successfully
2025-01-08 12:13:57,634 INFO     24 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-08 12:13:57,635 INFO     24 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-08 12:13:57,636 INFO     24 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-08 12:13:57,644 INFO     24 GET http://es01:9200/ [status:200 duration:0.006s]
2025-01-08 12:13:57,648 INFO     24 HEAD http://es01:9200/ [status:200 duration:0.003s]
2025-01-08 12:13:57,649 INFO     24 Elasticsearch http://es01:9200 is healthy.
2025-01-08 12:13:57,655 WARNING  24 Load term.freq FAIL!
2025-01-08 12:13:57,659 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 12:13:57,663 WARNING  24 Load term.freq FAIL!
2025-01-08 12:13:57,667 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 12:13:57,668 INFO     24 MAX_CONTENT_LENGTH: 134217728
2025-01-08 12:13:57,668 INFO     24 SERVER_QUEUE_MAX_LEN: 1024
2025-01-08 12:13:57,669 INFO     24 SERVER_QUEUE_RETENTION: 3600
2025-01-08 12:13:57,670 INFO     24 MAX_FILE_COUNT_PER_USER: 0
2025-01-08 12:13:57,683 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:13:57.682+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:14:27,714 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:14:27.714+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:14:57,746 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:14:57.745+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:15:03,954 INFO     24 handle_task begin for task {"id": "2248b572cd7711efaf060242ac130006", "doc_id": "1f78118acd7711efb6150242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "088f01c2cd7711efb36b0242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736309703187}
2025-01-08 12:15:03,968 INFO     24 From minio(0.007053861999793298) xlsl8.pdf/xlsl8.pdf
2025-01-08 12:15:07,414 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: None, progress_msg: 12:15:07 Page(1~4): OCR started
2025-01-08 12:15:10,333 WARNING  24 Miss outlines
2025-01-08 12:15:18,707 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: None, progress_msg: 12:15:18 Page(1~4): OCR finished (11.29s)
2025-01-08 12:15:18,714 INFO     24 OCR(0~3): 11.30s
2025-01-08 12:15:22,433 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: 0.63, progress_msg: 12:15:22 Page(1~4): Layout analysis (3.72s)
2025-01-08 12:15:22,612 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: 0.65, progress_msg: 12:15:22 Page(1~4): Table analysis (0.16s)
2025-01-08 12:15:22,625 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: 0.67, progress_msg: 12:15:22 Page(1~4): Text merged (0.00s)
2025-01-08 12:15:22,687 INFO     24 layouts cost: 15.275996587999998s
2025-01-08 12:15:22,796 INFO     24 naive_merge(xlsl8.pdf): 0.09877705700000661
2025-01-08 12:15:22,797 INFO     24 Chunking(18.83614186700015) xlsl8.pdf/xlsl8.pdf done
2025-01-08 12:15:22,912 INFO     24 MINIO PUT(xlsl8.pdf):0.06651144700026634
2025-01-08 12:15:22,913 INFO     24 Build document xlsl8.pdf: 18.95s
2025-01-08 12:15:22,916 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: None, progress_msg: 12:15:22 Page(1~4): Generate 8 chunks
2025-01-08 12:15:22,929 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: -1, progress_msg: 12:15:22 Page(1~4): [ERROR]Generate embedding error:list indices must be integers or slices, not tuple
2025-01-08 12:15:22,938 ERROR    24 Generate embedding error:list indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7fe279994160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7fe279ad01f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 12:15:22,944 INFO     24 set_progress(2248b572cd7711efaf060242ac130006), progress: -1, progress_msg: 12:15:22 [ERROR]handle_task got exception, please check log
2025-01-08 12:15:22,953 ERROR    24 handle_task got exception for task {"id": "2248b572cd7711efaf060242ac130006", "doc_id": "1f78118acd7711efb6150242ac130006", "from_page": 0, "to_page": 3, "retry_count": 0, "kb_id": "088f01c2cd7711efb36b0242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "xlsl8.pdf", "type": "pdf", "location": "xlsl8.pdf", "size": 432591, "tenant_id": "4648d13ccd6811ef93f20242ac130006", "language": "Vietnamese", "embd_id": "text-embedding-004@Gemini", "pagerank": 0, "img2txt_id": "gemini-1.0-pro-vision-latest@Gemini", "asr_id": "", "llm_id": "gemini-1.5-flash-latest@Gemini", "update_time": 1736309703187}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 513, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 463, in do_handle_task
    token_count, vector_size = embedding(chunks, embedding_model, task_parser_config, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 321, in embedding
    vts, c = mdl.encode(tts[i: i + batch_size])
  File "<@beartype(api.db.services.llm_service.LLMBundle.encode) at 0x7fe279994160>", line 31, in encode
  File "/ragflow/api/db/services/llm_service.py", line 238, in encode
    embeddings, used_tokens = self.mdl.encode(texts)
  File "<@beartype(rag.llm.embedding_model.GeminiEmbed.encode) at 0x7fe279ad01f0>", line 31, in encode
  File "/ragflow/rag/llm/embedding_model.py", line 508, in encode
    content=texts[i, i + batch_size],
TypeError: list indices must be integers or slices, not tuple
2025-01-08 12:15:27,778 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:15:27.776+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:15:57,784 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:15:57.783+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:16:27,788 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:16:27.787+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:16:57,793 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:16:57.792+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:17:27,824 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:17:27.823+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:17:57,838 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:17:57.837+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:18:27,868 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:18:27.868+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:18:57,873 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:18:57.872+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:19:27,897 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:19:27.896+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:19:57,905 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:19:57.904+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:20:27,937 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:20:27.936+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:20:57,945 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:20:57.944+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:21:27,947 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:21:27.947+08:00", "boot_at": "2025-01-08T12:13:57.634+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 1, "current": null}
2025-01-08 12:21:41,878 ERROR    24 RedisDB.queue_consumer rag_flow_svr_queue got exception: Connection closed by server.
Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 205, in queue_consumer
    messages = self.REDIS.xreadgroup(**args)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 4017, in xreadgroup
    return self.execute_command("XREADGROUP", *pieces)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 570, in execute_command
    response = conn.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 65, in call_with_retry
    fail(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 574, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 556, in _disconnect_raise
    raise error
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 571, in <lambda>
    lambda: self._send_command_parse_response(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 543, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 590, in parse_response
    response = connection.read_response()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 546, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
valkey.exceptions.ConnectionError: Connection closed by server.
2025-01-08 12:21:46,622 ERROR    24 RedisDB.get_unacked_for task_consumer_0 got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 12:21:50,348 ERROR    24 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error -2 connecting to redis:6379. Name or service not known.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
2025-01-08 12:24:15,877 INFO     24 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2025-01-08 12:24:21,118 INFO     24 init database on cluster mode successfully
2025-01-08 12:24:30,039 INFO     24 generated new fontManager
2025-01-08 12:24:40,003 INFO     24 
  ______           __      ______                     __            
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /    
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/                               
    
2025-01-08 12:24:40,004 INFO     24 TaskExecutor: RAGFlow version: v0.15.1 slim
2025-01-08 12:24:40,004 INFO     24 Use Elasticsearch http://es01:9200 as the doc engine.
2025-01-08 12:24:40,013 INFO     24 GET http://es01:9200/ [status:200 duration:0.008s]
2025-01-08 12:24:40,017 INFO     24 HEAD http://es01:9200/ [status:200 duration:0.003s]
2025-01-08 12:24:40,018 INFO     24 Elasticsearch http://es01:9200 is healthy.
2025-01-08 12:24:40,022 WARNING  24 Load term.freq FAIL!
2025-01-08 12:24:40,024 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 12:24:40,028 WARNING  24 Load term.freq FAIL!
2025-01-08 12:24:40,031 WARNING  24 Realtime synonym is disabled, since no redis connection.
2025-01-08 12:24:40,031 INFO     24 MAX_CONTENT_LENGTH: 134217728
2025-01-08 12:24:40,032 INFO     24 SERVER_QUEUE_MAX_LEN: 1024
2025-01-08 12:24:40,032 INFO     24 SERVER_QUEUE_RETENTION: 3600
2025-01-08 12:24:40,033 INFO     24 MAX_FILE_COUNT_PER_USER: 0
2025-01-08 12:24:40,048 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:24:40.047+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:25:10,079 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:25:10.078+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:25:40,081 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:25:40.081+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:26:10,093 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:26:10.092+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:26:40,123 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:26:40.123+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:27:10,155 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:27:10.154+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:27:40,158 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:27:40.158+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:28:10,188 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:28:10.188+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:28:40,219 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:28:40.218+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:29:10,250 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:29:10.250+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:29:40,280 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:29:40.279+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:30:10,311 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:30:10.310+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2025-01-08 12:30:40,339 INFO     24 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2025-01-08T12:30:40.338+08:00", "boot_at": "2025-01-08T12:24:40.003+08:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
